---
framework: mocha
preRun:
  command:
    - yarn install
    - NODE_ENV=production yarn build
preMerge:
  env:
    NODE_ENV: production
  pattern:
    - "./test/commands/**/*.js"
    - "./test/fixtures/**/*.js"
    - "./test/models/**/*.js"
    - "./test/plugins/**/*.js"
    - "./test/src/**/*.js"
    - "./test/tests/**/*.js"
    - "./test/*.js"
postMerge:
  env:
    NODE_ENV: production
  pattern:
    - "./test/commands/**/*.js"
    - "./test/fixtures/**/*.js"
    - "./test/models/**/*.js"
    - "./test/plugins/**/*.js"
    - "./test/src/**/*.js"
    - "./test/tests/**/*.js"
    - "./test/*.js"
postRun:
  command:
    - yarn --version
configFile: test/.mocharc.yml
version: 1.0
