---
framework: mocha
preRun:
  command:
    - yarn install
    - NODE_ENV=production yarn build
preMerge:
  pattern:
    - "./test/**/*.js"
postMerge:
  pattern:
    - "./test/**/*.js"
postRun:
  command:
    - yarn --version
configFile: mocharc.yml
version: 1.0
