---
framework: mocha
preRun:
  command:
    - yarn install
    - yarn build
preMerge:
  pattern:
    - "test/**/*.js"
postMerge:
  pattern:
    - "test/**/*.js"
postRun:
  command:
    - yarn --version
configFile: test/.mocharc.yml
version: 1.0
