---
framework: mocha
preRun:
  command:
    - yarn install
    - NODE_ENV=production yarn build
preMerge:
  pattern:
    - "./test/*/{*.js,!(client)/**/*.js}"
postMerge:
  pattern:
    - "./test/*/{*.js,!(client)/**/*.js}"
postRun:
  command:
    - yarn --version
configFile: test/.mocharc.yml
version: 1.0
